
import { GoogleGenAI } from "@google/genai";

const getAI = () => new GoogleGenAI({ apiKey: process.env.API_KEY || '' });

export const transformImage = async (
  base64Image: string,
  mode: 'HEADSHOT' | 'PASSPORT',
  options: { background: string; attire: string }
): Promise<string> => {
  const ai = getAI();
  const model = 'gemini-2.5-flash-image';

  const prompt = mode === 'HEADSHOT' 
    ? `Transform the person in this image into a high-quality professional corporate headshot. 
       The person should be wearing ${options.attire}. 
       The background should be ${options.background}. 
       Maintain the facial identity perfectly but enhance skin clarity, lighting, and overall professional look. 
       The output should be a centered, well-lit studio-style portrait suitable for LinkedIn or a CV.`
    : `Transform this image into a standard official passport photo. 
       The background must be a solid, flat ${options.background}. 
       The person should be front-facing with a neutral expression and professional appearance. 
       The lighting must be even across the face with no shadows. 
       The attire should be ${options.attire}. 
       Ensure the head is centered and scaled according to international passport standards.`;

  try {
    const response = await ai.models.generateContent({
      model: model,
      contents: {
        parts: [
          {
            inlineData: {
              data: base64Image.split(',')[1],
              mimeType: 'image/png',
            },
          },
          { text: prompt },
        ],
      },
    });

    let imageUrl = '';
    for (const part of response.candidates[0].content.parts) {
      if (part.inlineData) {
        imageUrl = `data:image/png;base64,${part.inlineData.data}`;
        break;
      }
    }

    if (!imageUrl) {
      throw new Error("No image was generated by the model.");
    }

    return imageUrl;
  } catch (error) {
    console.error("Gemini Image Transformation Error:", error);
    throw error;
  }
};
